# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/marble/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),marble)

$(call add-radio-file-sha1-checked,radio/abl.img,6f3b39742d92d507194ae09fa3a2201cbd7f3c20)
$(call add-radio-file-sha1-checked,radio/aop.img,1079a66d4e52da82d582554b6f12c2745efd2627)
$(call add-radio-file-sha1-checked,radio/aop_config.img,8ea8af9b4f3342ea2f4ecb471fca70976af9c903)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d8eeb75675077dd73da560c699abedb2a65b34c7)
$(call add-radio-file-sha1-checked,radio/cpucp.img,b40ceb9b0050586ccc94d9eb5c5415a83adc2cdf)
$(call add-radio-file-sha1-checked,radio/devcfg.img,7eb44240b6539846c07a135f7d6f6c7e0c786c24)
$(call add-radio-file-sha1-checked,radio/dsp.img,abb0cf432db0d513601b5314b55b1765dc900317)
$(call add-radio-file-sha1-checked,radio/featenabler.img,c692c9a173750caeaf20c9b6a174e7947ab3733a)
$(call add-radio-file-sha1-checked,radio/hyp.img,613f72696ecebd92f19bb0a2000ca00c8b7d3bc8)
$(call add-radio-file-sha1-checked,radio/imagefv.img,4932462b9b0960b70ad84922b0ded5d7e409955f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,4f9c3f7b15189b9cebd66f0609f44a8e1b977885)
$(call add-radio-file-sha1-checked,radio/modem.img,3195664632b3b88b1d38c8455d1f54dc65c1d5e1)
$(call add-radio-file-sha1-checked,radio/qupfw.img,d3e0e8427f193c9aa083ce81f8dfd2085395de64)
$(call add-radio-file-sha1-checked,radio/shrm.img,1c3762171d5322456b6c7952cae4b4eea72f0e35)
$(call add-radio-file-sha1-checked,radio/tz.img,4f8f1f65d3ddd15f35d17a1c880517ca38517017)
$(call add-radio-file-sha1-checked,radio/uefi.img,d928117aa3bcfde16efdb292b1c909a6c5b14eeb)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,09872b94ccb3bde5d406e964947a03be1f514d5a)
$(call add-radio-file-sha1-checked,radio/xbl.img,75b27b57e82b085b6427d9381d0200bd5e7f8d37)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,f3fc02a61b93bb6e5e371160ae8d1a9aa568f2af)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,85935445699e15a40cb8ed3d0f2951887cc3cee3)

endif
