# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/marble/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),marble)

$(call add-radio-file-sha1-checked,radio/abl.img,c799ee6ba2bc99001041e93edf7d781f898d82f2)
$(call add-radio-file-sha1-checked,radio/aop.img,97cedd55a0ab760b017ab9108549b964f0b52671)
$(call add-radio-file-sha1-checked,radio/aop_config.img,442c6b84c0295f65f87ca15314f45b29a7444e5f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b6e51056efa5d29200557dcfdc080ec0c3086671)
$(call add-radio-file-sha1-checked,radio/cpucp.img,40e8a0fad844ff50020d153a02536372fc4bd422)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c227fee30f391d22406c19b0111017da5e48a0ab)
$(call add-radio-file-sha1-checked,radio/dsp.img,abb0cf432db0d513601b5314b55b1765dc900317)
$(call add-radio-file-sha1-checked,radio/featenabler.img,392baf097236aca407970bf97909f5348c5b4a77)
$(call add-radio-file-sha1-checked,radio/hyp.img,229186006235985435d9996307bd0fff82e6c484)
$(call add-radio-file-sha1-checked,radio/imagefv.img,b48e92a36e3399c1ca3230a75ec7e26d112e2250)
$(call add-radio-file-sha1-checked,radio/keymaster.img,faadb0ad5049423a857217d3667383039e33e642)
$(call add-radio-file-sha1-checked,radio/modem.img,e5246044cc0969d0a0476ce50bc957f7dda2a7f7)
$(call add-radio-file-sha1-checked,radio/qupfw.img,aec9aa062c61f97f32b41a3b941d12da73e89832)
$(call add-radio-file-sha1-checked,radio/shrm.img,1977cab222c6acda744a81279b356d97fa13ec96)
$(call add-radio-file-sha1-checked,radio/tz.img,d11551b2306495831ace55d0c1744ffc4135ba4a)
$(call add-radio-file-sha1-checked,radio/uefi.img,886da4cd79be49673b3715d2a44227f52a8bf8a0)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,633d6cdd98c89c7e09bf7313ea98d19ef77c2914)
$(call add-radio-file-sha1-checked,radio/xbl.img,a24fbfa63f2da65f3cc9271f6fab48b6a8a7f684)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,e3ed2c0144a8eb029333af1d8a028387bde4865c)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,9cce2b3fc9a1f4900791772ce21e36b3cd706f62)

endif
