# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/marble/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),marble)

$(call add-radio-file-sha1-checked,radio/abl.img,c29a00da0fbd94350d9b5169d2d092f6b49a7971)
$(call add-radio-file-sha1-checked,radio/aop.img,c4f9a55bcdf0a30369507c09b2275eb7763fa8f9)
$(call add-radio-file-sha1-checked,radio/aop_config.img,4fe008824c106e6e972086523d6377a0ea8cc611)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,47cefcafea01a02fad42554f97190717bc916fae)
$(call add-radio-file-sha1-checked,radio/cpucp.img,29061f2511552c80a09d6154eb2d43e3b4f8e94a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,5b944a4ef05ab446068ba3a109f27884faa09768)
$(call add-radio-file-sha1-checked,radio/dsp.img,abb0cf432db0d513601b5314b55b1765dc900317)
$(call add-radio-file-sha1-checked,radio/featenabler.img,a1d20686bb601aed4f0464b3da22100652154e0c)
$(call add-radio-file-sha1-checked,radio/hyp.img,bda8db160361e36b15e7ccae983cf9b921ca2693)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f031158eedaf9b61e0ad44f3bd703fde64a831d5)
$(call add-radio-file-sha1-checked,radio/keymaster.img,37e963edc5380be0e19a56715fb26f8cb8471e87)
$(call add-radio-file-sha1-checked,radio/modem.img,6c8661b2ab25abe2d695335c244b38ac489b83d5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,502aa0a67d88df7eed27341cb6478ede84b6d557)
$(call add-radio-file-sha1-checked,radio/shrm.img,24ff166fec2311bccc8f99078898c73f21e982d4)
$(call add-radio-file-sha1-checked,radio/tz.img,ff29b8402360100960ab8e12d942734557d969ee)
$(call add-radio-file-sha1-checked,radio/uefi.img,51b335d4206a6e184f5b993f9c7d86649675435c)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,81090fb8598d1b96f730ac10ae6b5d3feeeb4069)
$(call add-radio-file-sha1-checked,radio/xbl.img,95a3927d9ac6334b922fecf76713b259cda0c836)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,60006d38e52618aaddad737328d8e438a0a13e1e)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,9728302e95adccff2f449124c62fd2deb81d211a)

endif
